---
title: "Beta Regression"
author: "John Tipton"
date: "August 14, 2015"
output: html_document
---

# Catch by gender 
Not sure of the story here. There is definitely an effect of gender, but I suspect this is due to non-random misclassification into the unknowns (i.e. the unknowns are more likely to be females (males) than males (females))

# Write a beta GLM in STAN

```{r}
library(rstan)
sm <- stan_model("~/mysis/stanModels/negbin-glm.stan")
```

## Load the Data

```{r}
library(ggplot2)
set.seed(123)

fullData <- read.csv("~/mysis/data/lengthData.csv", skip=4)

males <- rep(0, 80)
females <- rep(0, 80)
juveniles <- rep(0, 80)
unknowns <- rep(0, 80)
size <- rep(0, 80)
date_tmp <- rep(0, 80)

idx <- 1
for(i in unique(fullData$Sample.Label)){
  tmp_data = subset(fullData, fullData$Sample.Label == i)
  tmp = substr(as.character(tmp_data$Gender), 0, 1)
  males[idx] <- sum(tmp == "M")
  juveniles[idx] <- sum(tmp == "J")
  females[idx] <- sum(tmp == "F")
  unknowns[idx] <- sum(tmp == "U")
  size[idx] <- tmp_data$Size..m.[1]
  date_tmp[idx] <- tmp_data$Date[1]
  idx <- idx + 1
}

## construct count vector
count <- c(males, females, juveniles, unknowns)
gender <- factor(rep(1:4, each=80))
## Correct for mislabeling
date_tmp[70] <- 4
date_tmp[72] <- 4
date <- rep(0, 80)
date[date_tmp == 1] <- 1
date[date_tmp == 2] <- 1
date[date_tmp == 3] <- 2
date[date_tmp == 4] <- 3



date <- as.factor(date)
net <- as.factor(size)
count[rep(net, times=4) == 0.5] <- count[rep(net, times=4) == 0.5] * 4
data <- data.frame(count=count, date=rep(date, times=4), net=rep(net, times=4), gender=gender)
# X <- model.matrix(~ net * date + net * gender + gender * date, data=data)
X <- model.matrix(~ net + net * gender + gender * date, data=data)
ggplot(data=data, aes(count)) + geom_histogram() + facet_grid(net ~ gender)
ggplot(data=data, aes(count)) + geom_histogram() + facet_grid(net ~ date)
ggplot(data=data, aes(count)) + geom_histogram() + facet_grid(gender ~ date)

```

## Fit the Model

```{r}
m <- sampling(sm, data = list(N=320, y=count, X=X, p=dim(X)[2]),
  pars = c("beta", "phi"),
  iter = 5000, chains = 4)
```

## Model output
```{r}
m
```

## Plot traceplots
```{r}
rstan::traceplot(m, inc_warmup = FALSE)
```

## Plot fitted vs. simulated values

```{r}
e <- rstan::extract(m, pars = c("beta", "phi"))
library(MASS)
nbmod <- glm.nb(y ~ . -1, data = data.frame(y=count, X))
summary(nbmod)
coefs <- c(nbmod$coefficients, nbmod$theta)
par(mfrow = c(3, 3))
for(i in 1:2) {
  if(i == 1){
    for(j in 1:dim(e[[i]])[2]) {
      plot(density(e[[i]][,j]), main = paste("beta", j, sep=""))
      abline(v = coefs[j], lwd = 3, col = "red")
    }
  } else if(i == 2) {
    plot(density(e[[i]]), main = paste("phi"))
    abline(v = coefs[dim(e[[i]])[2] + 1], lwd = 3, col = "red")
  }
}

```


```{r}
library(ggmcmc)
library(coda)
s <-  mcmc.list(lapply(1:ncol(m), function(x) mcmc(as.array(m)[,x,])))
S <- ggs(s)

ggs_caterpillar(S, family = "beta") 

```





