# Site settings
title: John Tipton
email: jtipton25@gmail.com
description: ""

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jtipton25.github.io" # the base hostname & protocol for your site
github_username:  jtipton25

# Build settings
markdown: kramdown
highlighter: pygments
