---
title: "negativeBinomial"
author: "John Tipton"
date: "August 14, 2015"
output: html_document
---

# Write a negative binomial GLM in STAN

```{r}
library(rstan)
model <- "
// Negative Binomial GLM
// see Gelman and Hill (2007)
data {
  int<lower=1> N;       // number of observations
  int<lower=0> p;
  matrix[N, p] X;       // predictor
  int<lower=0> y[N];    // response
} transformed data {
  vector[p] J;
  matrix[p, p] I_p;
  // calculate placeholder values
  J <- rep_vector(0, p);
  I_p <- diag_matrix(rep_vector(1, p));
}
parameters {
  real<lower=0> phi;   // Negative Binomial dispersion parameter
  vector[p] beta;      // Negative Binomial mean parameters
} model {
  // priors:
  phi ~ cauchy(0, 20);
  beta ~ multi_normal(J, 100 * I_p);
  // data model:
  y ~ neg_binomial_2_log(X * beta, phi);
}
"
write(model, file = "~/mysis/stanModels/overdispersedPoisson-glm.stan")
sm <- stan_model("~/mysis/stanModels/overdispersedPoisson-glm.stan")
```

## Simulate some Data

```{r}
set.seed(123)
N <- 80
phi <- 1
# beta <- c(1, 2, -1, 1, -2, -1)
beta <- c(2, -1, 1, -2, -1)
x0 <- rep(1, N)
x1 <- c(rep(1, N/2), rep(0, N/2)) ## Indicator for net size
x2 <- rep(c(rep(1, 10), rep(0, 30)), 2) ## Indicator for July
x3 <- rep(c(rep(0, 10), rep(1, 20), rep(0, 10)), 2) ## Indicator for August
# x4 <- rep(c(rep(0, 30), rep(1, 10)), 2) ## Indicator for September
x12 <- x1 * x2 ## Interaction between net size and July
x13 <- x1 * x3 ## Interaction between net size and August
# X <- cbind(x0, x1, x2, x3, x12, x13)
X <- cbind(x1, x2, x3, x12, x13)
y <- rnbinom(N, size=phi, mu=exp(X %*% beta))
layout(matrix(c(1, 1, 2, 3), 2, 2, byrow=TRUE))
hist(y)
hist(y[x1 == 0])
hist(y[x1 == 1])
```

## Fit the Model

```{r}
m <- sampling(sm, data = list(N = N, y = y, X = X, p=dim(X)[2]),
  pars = c("beta", "phi"),
  iter = 5000, chains = 4)
```

## Model output
```{r}
m
```

## Plot traceplots
```{r}
rstan::traceplot(m, inc_warmup = FALSE)
```

## Plot fitted vs. simulated values

```{r}
e <- rstan::extract(m, pars = c("beta", "phi"))
true_pars <- c(beta=beta, phi=phi)
m2 <- MASS::glm.nb(y ~ X-1)
coefs <- c(coef(m2), summary(m2)$theta)
par(mfrow = c(2, 3))
for(i in 1:2) {
  if(i == 1) {
#     for(j in 1:6) {
    for(j in 1:5) {
      plot(density(e[[i]][,j]), main = names(true_pars)[j])
      abline(v = true_pars[j], lwd = 2, col = "grey", lty = 2)
      abline(v = coefs[j], lwd = 3, col = "red")
    }
  } else if(i == 2) {
    plot(density(e[[i]]), main = names(true_pars)[j + 1])
    abline(v = true_pars[j + 1], lwd = 2, col = "grey", lty = 2)
    abline(v = coefs[j + 1], lwd = 3, col = "red")
  }
}
# legend("topright", legend = c("posterior", "true", "MASS::glm.nb"),
#   col = c("black", "grey", "red"), lty = c(1, 2, 1), lwd = c(1, 1.3, 3),
#   bty = "n")
```


```{r}
library(ggmcmc)
library(coda)
s <-  mcmc.list(lapply(1:ncol(m), function(x) mcmc(as.array(m)[,x,])))
S <- ggs(s)

idx <- order(colMeans(e$beta))

ggs_caterpillar(S, family = "beta") + 
  geom_point(aes(y=1:5, x=beta[idx]), col = "red")
```

