---
title: "negativeBinomial"
author: "John Tipton"
date: "August 14, 2015"
output: html_document
---

## Load the data - are these dates errors or are the samples that were found later in the season

```{r}
library(ggplot2)
library(stringr)
library(mgcv)
set.seed(123)
data_length <- read.csv("~/mysis/data/lengthData.csv", skip = 4, header = TRUE)
net <- data_length$Size..m.
y <- data_length$Length..mm.
gender <- as.factor(substr(str_trim(as.character(data_length$Gender)), 0, 1))
                       ## remove whitespace from string, then truncate into 
                       ## broad gender classes, not subclasses

date <- as.numeric(data_length$Date)
date[date == 2] <- 1      ## collapse into monthly values
date[date == 3] <- 2
date[date == 4] <- 3
date <- as.factor(date)
plot(as.numeric(date), type='l', main = "Is this a data error? - yes?")
## correct date mislabeling
date <- as.numeric(data_length$Date)
date[7330:7519] <- 4
date[7559:7773] <- 4
date[date == 2] <- 1      ## collapse into monthly values
date[date == 3] <- 2
date[date == 4] <- 3
date <- as.factor(date)
plot(as.numeric(date), type='l', main = "Data looks better")
data <- data.frame(y=y, date=date, net=net, gender=gender)
X <- model.matrix(~ net + date + gender, data=data)
ggplot(data=data, aes(y)) + geom_histogram() + facet_grid(net ~ date)
idx <- attr(uniquecombs(X), "index")
```

# Write the model
$t$ = time
$i$ = net size
$j$ = age class
$k$ = replicate

$$
y_{tijk} \sim \mbox{N}(\mu_{tij}, \sigma^2_{tij})
$$

```{r, echo=FALSE}
library(rstan, verbose=FALSE)
model <- "
// regression
data {
  int<lower=1> N;             // number of observations
  int<lower=1> p;             // number of predictors
  int<lower=1> q;             // number of levels
  matrix[N, p] X;             // predictor
  vector[N] y;                // response
  int idx[N];                 // indicator variable of treatment
} parameters {  
  vector<lower=0>[q] s;       // heterogeneous regression standard deviation
  vector[p] beta;             // mean parameters
} model {
  // priors:
  //s ~ cauchy(0, 20);
  for(i in 2:p){
    beta[i] ~ normal(0, 100);
  }

  // data model:
  for(i in 1:N){
    y[i] ~ normal(X[i] * beta, s[idx[i]]);
  }
}
"
write(model, file = "~/mysis/stanModels/lengthHeterogeneous.stan")
# sm <- stan_model("~/mysis/stanModels/lengthHeterogeneous.stan")
sm <- stan("~/mysis/stanModels/lengthHeterogeneous.stan", 
           data=list(N=length(y), p=dim(X)[2], y=y, X=X, idx=idx, q=length(unique(idx))),
           chains=0)
```
## Fit the Model

```{r, echo=FALSE, cache=TRUE}
library(parallel)
estimate_params <- function(model, data, pars = pars, iter=5000){
  sflist <- mclapply(1:4, mc.cores = 4,
             function(i) stan(fit = model, data = data, pars = pars,
                              chains = 1, chain_id = i,
                              iter=iter,
                              refresh = -1))
  fit <- sflist2stanfit(sflist)
  return(fit)
}
# m <- sampling(sm, data = list(N=length(y), p=dim(X)[2], y=y, X=X, idx=idx, q=length(unique(idx))),
#   pars = c("beta", "s"),
#   iter = 1000, chains = 1)
m <- estimate_params(sm, data = list(N=length(y), p=dim(X)[2], y=y, X=X, idx=idx, q=length(unique(idx))),
                     pars = c("beta", "s"))
```

## Model output
```{r}
m
```

## Plot traceplots
```{r}
rstan::traceplot(m, inc_warmup = FALSE)
```

## Plot fitted vs. simulated values

```{r}
e <- rstan::extract(m, pars = c("beta", "s"))
par(mfrow = c(3, 3))
for(i in 1:2) {
  if(i == 1) {
    for(j in 1:dim(e[[i]])[2]) {
      plot(density(e[[i]][,j]), main = paste("beta", j, sep=""))
    }
  } else if(i == 2) {
    plot(density(e[[i]]), main = "s")
  }
}
```


```{r}
library(ggmcmc)
library(coda)
s <-  mcmc.list(lapply(1:ncol(m), function(x) mcmc(as.array(m)[,x,])))
S <- ggs(s)


ggs_caterpillar(S, family = "beta") 
```


```{r}
library(Gmisc)
tableData <- cbind(summary(s)$statistics[1:(dim(e[[1]])[2] + 1), 1],
                   summary(s)$quantiles[1:(dim(e[[1]])[2] + 1), c(1, 5)])
htmlTable(x=round(tableData, digits=2),
          caption=paste("Regression parameter estimates and CI's"),
          header = c("Estimate", "Lower 95% CI", "Upper 95% CI"),
          rowlabel = "Variables",
          rnames = c("Intercept",
                    "Net Size",
                    "August",
                    "September",
                    "Juvenile",
                    "Male",
                    "Unknown",
                    "standard deviation"))
```


```{r}
summary(lm(y ~ net + date + gender))
plot(lm(y ~ net + date + gender))
library(MASS)
summary(rlm(y ~ net + date + gender))
plot(rlm(y ~ net + date + gender))
```
