---
title: "negativeBinomial"
author: "John Tipton"
date: "August 14, 2015"
output: html_document
---

## Load the data

```{r}
library(ggplot2)
set.seed(123)
data_length <- read.csv("~/mysis/data/lengthData.csv", skip = 4, header = TRUE)
net <- data_length$Size..m.
length <- data_length$Length..mm.
gender <- as.factor(substr(as.character(data_length$Gender), 0, 1))
# data_one_way$full ## count per m^2 for full net
# data_one_way$half ## count per m^2 for half net
count <- c(data_one_way$full.5,  ## count for full net
            4 * data_one_way$half.5) ## count for half net adjusted for radius
date <- rep(as.factor(data_one_way$month), 2)
net <- as.factor(c(rep("full", 40), rep("half", 40)))
data <- data.frame(count=count, date=date, net=net)
X <- model.matrix(~ net * date)
ggplot(data=data, aes(count)) + geom_histogram() + facet_grid(net ~ .)
```

# Write a negative binomial GLM in STAN

```{r, echo=FALSE}
library(rstan, verbose=FALSE)
# model <- "
# // Negative Binomial GLM
# // see Gelman and Hill (2007)
# data {
#   int<lower=1> N;       // number of observations
#   int<lower=0> p;
#   matrix[N, p] X;       // predictor
#   int<lower=0> y[N];    // response
# } transformed data {
#   vector[p] J;
#   matrix[p, p] I_p;
#   // calculate placeholder values
#   J <- rep_vector(0, p);
#   I_p <- diag_matrix(rep_vector(1, p));
# }
# parameters {
#   real<lower=0> phi;   // Negative Binomial dispersion parameter
#   vector[p] beta;      // Negative Binomial mean parameters
# } model {
#   // priors:
#   phi ~ cauchy(0, 20);
#   beta ~ multi_normal(J, 100 * I_p);
#   // data model:
#   y ~ neg_binomial_2_log(X * beta, phi);
# }
# "
# write(model, file = "~/mysis/stanModels/negbin-glm.stan")
# sm <- stan_model("~/mysis/stanModels/negbin-glm.stan")
sm <- stan("~/mysis/stanModels/negbin-glm.stan", 
           data=list(N = length(count), y = count, X = X, p=dim(X)[2]),
           chains=0)
```
## Fit the Model

```{r, echo=FALSE}
library(parallel)
estimate_params <- function(model, data, pars = pars, iter=5000){
  sflist <- mclapply(1:4, mc.cores = 4,
             function(i) stan(fit = model, data = data, pars = pars,
                              chains = 1, chain_id = i,
                              iter=iter,
                              refresh = -1))
  fit <- sflist2stanfit(sflist)
  return(fit)
}
# m <- sampling(sm, data = list(N = length(count), y = count, X = X, p=dim(X)[2]),
#   pars = c("beta", "phi"),
#   iter = 5000, chains = 4)
m <- estimate_params(sm, data = list(N = length(count), y = count, X = X, p=dim(X)[2]),  pars = c("beta", "phi"))
```

## Model output
```{r}
m
```

## Plot traceplots
```{r}
rstan::traceplot(m, inc_warmup = FALSE)
```

## Plot fitted vs. simulated values

```{r}
e <- rstan::extract(m, pars = c("beta", "phi"))
par(mfrow = c(2, 3))
for(i in 1:2) {
  if(i == 1) {
#     for(j in 1:6) {
    for(j in 1:5) {
      plot(density(e[[i]][,j]), main = paste("beta", j, sep=""))
    }
  } else if(i == 2) {
    plot(density(e[[i]]), main = "phi")
  }
}
```


```{r}
library(ggmcmc)
library(coda)
s <-  mcmc.list(lapply(1:ncol(m), function(x) mcmc(as.array(m)[,x,])))
S <- ggs(s)


ggs_caterpillar(S, family = "beta") 
```


```{r}
library(Gmisc)
tableData <- cbind(summary(s)$statistics[1:7, 1], summary(s)$quantiles[1:7, c(1, 5)])
htmlTable(x=round(tableData, digits=2),
          caption=paste("Regression parameter estimates and CI's"),
          header = c("Estimate", "Lower 95% CI", "Upper 95% CI"),
          rowlabel = "Variables",
          rnames = c("Intercept",
                    "Net Size",
                    "August",
                    "September",
                    "Net Size by August",
                    "Net Size by September",
                    "Overdispersion Parameter"))
```

